"""First migration

Revision ID: bc693a1a7591
Revises: 
Create Date: 2022-01-26 23:08:13.946190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc693a1a7591'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    with op.batch_alter_table('lidmasina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razosanas_gads', sa.String(length=3), nullable=False))
        batch_op.add_column(sa.Column('vietu_skaits', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.drop_column('vietuSkaits')
        batch_op.drop_column('ražošanasGads')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lidmasina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ražošanasGads', sa.VARCHAR(length=3), nullable=False))
        batch_op.add_column(sa.Column('vietuSkaits', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('date_created')
        batch_op.drop_column('vietu_skaits')
        batch_op.drop_column('razosanas_gads')

    op.create_table('todo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(length=200), nullable=False),
    sa.Column('saisinajums', sa.VARCHAR(length=3), nullable=False),
    sa.Column('adrese', sa.VARCHAR(length=200), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
